import os
import glob

configfile: "config.yaml"

PATIENTS_DIR = config["patients_dir"]
RESULTS_DIR = config["results_dir"]

SUBJECTS = [
    os.path.basename(p)
    for p in glob.glob(os.path.join(PATIENTS_DIR, "sub-*"))
]

rule all:
    input:
        expand(
            os.path.join(RESULTS_DIR, "{pid}"),
            pid=SUBJECTS
        )

rule run_simulation:
    input:
        lambda wc: os.path.join(PATIENTS_DIR, wc.pid)
    output:
        directory(os.path.join(RESULTS_DIR, "{pid}"))
    threads: 1
    shell:
        """
        python run_simulation.py \
            {wildcards.pid} \
            {input}
        """
