# ------------------------
# Subjects
# ------------------------

subjects: 
- sub-HC01
- sub-HC02
- sub-HC03
- sub-HC04
- sub-HC05
- sub-HC07
- sub-HC08
- sub-HC09
- sub-HC10
- sub-HC11
- sub-HC12
- sub-HC13
- sub-HC14
- sub-HC15
- sub-HC17
- sub-HC18
- sub-HC19
- sub-HC21
- sub-HC22
- sub-HC23
- sub-HC24
- sub-HC25
- sub-HC27
- sub-HC28
- sub-HC30
- sub-HC31
- sub-HC32
- sub-HC33
- sub-HC34
- sub-HC35
- sub-HC36
- sub-HC37
- sub-HC38
- sub-HC39
- sub-HC40
- sub-HC41
- sub-HC42
- sub-HC43
- sub-HC45
- sub-HC46
- sub-HC47
- sub-HC50
- sub-HC51
- sub-HC53
- sub-HC54
- sub-HC55
- sub-HC56
- sub-HC57
- sub-HC58
- sub-HC59
- sub-HC60
- sub-HC61
- sub-HC62
- sub-HC63
- sub-HC64
- sub-HC65
- sub-HC66
- sub-HC67
- sub-HC69
- sub-SCZ01
- sub-SCZ02
- sub-SCZ03
- sub-SCZ04
- sub-SCZ05
- sub-SCZ06
- sub-SCZ11
- sub-SCZ12
- sub-SCZ13
- sub-SCZ14
- sub-SCZ17
- sub-SCZ21
- sub-SCZ22
- sub-SCZ24
- sub-SCZ25
- sub-SCZ27
- sub-SCZ28
- sub-SCZ29
- sub-SCZ31
- sub-SCZ32
- sub-SCZ33
- sub-SCZ34
- sub-SCZ35
- sub-SCZ36
- sub-SCZ37
- sub-SCZ38
- sub-SCZ39
- sub-SCZ40
- sub-SCZ41
- sub-SCZ42
- sub-SCZ43
- sub-SCZ44
- sub-SCZ45
- sub-SCZ47
- sub-SCZ48
- sub-SCZ49

# ------------------------
# Sweep parameters
# ------------------------

we_values: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45]
sigma_values: [0.001, 0.003, 0.006, 0.01, 0.03, 0.06, 0.1, 0.3, 0.6, 1.0]
Ja_values: [0., 3., 6., 9., 12., 15., 18., 21., 24., 27.]